-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: requirements-txt-fixer
-   repo: git://github.com/pre-commit/mirrors-scss-lint
    rev: a1648868c160f1ca0acedef6dc51541c91ee04c6
    hooks:
    -   id: scss-lint
